# -*- coding: utf-8 -*-
"""Housing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZkvtPMJtBgwjG5-ncpwmV623HicYk9T7
"""

import pandas as pd
import csv

!pwd
import os
#os.chdir('data/')
!pwd
!ls

df = pd.read_csv('processed/hillsborough_fl_processed_2017_to_2019_20210225.csv') 
df.info()

df = df[df["total-households"] > 0]
display(df)

df['fc_rate'] = df['total-foreclosure-sales']/df['total-owner-occupied-households-mortgage']
df['ev_rate'] = 1.0*df['total-evictions']/df['total-renter-occupied-households']

df['fc_rate'].describe(percentiles=[.01, 0.05, 0.20, 0.40, 0.60, 0.80, 0.95, 0.99])

df['ev_rate'].describe(percentiles=[.01, 0.05, 0.20, 0.40, 0.60, 0.80, 0.95, 0.99])

#Overall foreclosure rate and eviction rate

overall_fc = df['total-evictions'].sum() / df['total-renter-occupied-households'].sum()
overall_ev = df['total-foreclosure-sales'].sum() / df['total-owner-occupied-households-mortgage'].sum()

print( 'Overall foreclosure rate:', overall_fc)

print( 'Overall eviction rate:', overall_ev)

df.info()



df.describe()





"""(Hillsborough) What is the overall eviction rate for this time period (i.e.,s/renting households)? What is the overall foreclosure rate for this time period (i.e. foreclosures/households with a mortgage)?

(Hillsborough) What is the overall eviction rate for this time period (i.e.,s/renting households)? What is the overall foreclosure rate for this time period (i.e. foreclosures/households with a mortgage)?
"""
